### ISSUE TITLE
Non-smooth transition

### ISSUE THREAD

**Issue by aiceyyyy** [F4eNn/React-Navbar-Effects#1]
Hello F4eN. 
Your project is great, however there is a small bug. When you hover over a navigation element for the first time, the effect "jumps" not very smoothly, which looks average in my opinion. As for the rest, I have no objections.  I wish you answer me back what do you think about it and if you spotted where the problem is.
Greetings from 
kubson52

**Comment by Matkolit** [comment]
I've made the necessary adjustments, and now the effect should smoothly appear on the first hover as well. If you encounter any more issues or have further suggestions, please feel free to let me know. Your feedback helps me improve this project 👍🏻 

Best regards,
F4eN
